site_url: https://klaudiarafal.pl
site_name: Klaudia & Rafał
site_description: Klaudia & Rafał
site_author: Rafał Schmidt
copyright: Rafał Schmidt

extra:
  generator: false # "Made with Material"

docs_dir: src

theme:
  name: material
  favicon: assets/images/favicon-32x32.png
  custom_dir: src/theme
  static_templates:
    - home.html
  language: pl
  # locale: pl

extra_css:
  - assets/stylesheets/variables.css
  - assets/stylesheets/main-overrides.css
  - assets/stylesheets/page.css
  - assets/stylesheets/home.css
  - assets/stylesheets/cookies.css

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      auto_title: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink

nav:
  - "": "index.md"

exclude_docs: |
  drafts/

plugins:
  - git-revision-date-localized:
      custom_format: "%d.%m.%Y"
      type: custom
      locale: pl
      enable_creation_date: true
      fallback_to_build_date: true
      exclude:
        - index.md
        - tagi.md
  - minify:
      minify_html: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
          remove_optional_attribute_quotes: false
      cache_safe: true
      css_files:
          - assets/stylesheets/variables.css
          - assets/stylesheets/main-overrides.css
          - assets/stylesheets/page.css
          - assets/stylesheets/home.css
          - assets/stylesheets/cookies.css